import * as THREE from 'three';
function rng(seed=1){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function shadows(g){g.traverse(n=>{if(n.isMesh){n.castShadow=true;n.receiveShadow=true}});return g}
const bark=new THREE.MeshStandardMaterial({color:0x5a3b24,roughness:.98});
const darkNeedle=new THREE.MeshStandardMaterial({color:0x17472d,roughness:.94,side:THREE.DoubleSide});
const midNeedle=new THREE.MeshStandardMaterial({color:0x28633a,roughness:.93,side:THREE.DoubleSide});
const lightNeedle=new THREE.MeshStandardMaterial({color:0x4d8349,roughness:.91,side:THREE.DoubleSide});
const rockMats=[0x555c5d,0x69706d,0x7c7d72,0x4c5552].map(c=>new THREE.MeshStandardMaterial({color:c,roughness:.96}));
const soil=new THREE.MeshStandardMaterial({color:0x5f5038,roughness:1});
const moss=new THREE.MeshStandardMaterial({color:0x59713b,roughness:1});
const grass=new THREE.MeshStandardMaterial({color:0x5f8b3d,roughness:1,side:THREE.DoubleSide});
const grassLight=new THREE.MeshStandardMaterial({color:0x86a94b,roughness:1,side:THREE.DoubleSide});
const flowerWhite=new THREE.MeshStandardMaterial({color:0xf6efd7,roughness:.8});
const flowerPink=new THREE.MeshStandardMaterial({color:0xe7a3b0,roughness:.8});
function deform(g,r,a=.24){const p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i);p.setXYZ(i,x*(1+(r()-.5)*a),y*(1+(r()-.5)*a*.75),z*(1+(r()-.5)*a))}p.needsUpdate=true;g.computeVertexNormals();return g}
function makeGrassMap(seed=1,rx=3,ry=3){const r=rng(seed),c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d');x.fillStyle='#668b42';x.fillRect(0,0,256,256);for(let i=0;i<75;i++){const px=r()*256,py=r()*256,rad=10+r()*36,g=x.createRadialGradient(px,py,0,px,py,rad);g.addColorStop(0,i%3===0?'rgba(173,187,86,.19)':i%3===1?'rgba(43,91,48,.18)':'rgba(117,132,61,.16)');g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.beginPath();x.arc(px,py,rad,0,Math.PI*2);x.fill()}for(let i=0;i<2600;i++){const px=r()*256,py=r()*256,l=.6+r()*2.4;x.strokeStyle=i%5===0?'rgba(218,220,126,.28)':i%3===0?'rgba(41,79,35,.34)':'rgba(119,156,68,.30)';x.lineWidth=.45+r()*.8;x.beginPath();x.moveTo(px,py);x.lineTo(px+(r()-.5)*2.2,py-l);x.stroke()}for(let i=0;i<120;i++){x.fillStyle=i%3===0?'rgba(92,70,43,.18)':'rgba(235,225,153,.20)';x.beginPath();x.arc(r()*256,r()*256,.45+r()*1.4,0,Math.PI*2);x.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(rx,ry);t.anisotropy=4;return t}
function frondGeometry(len=.9,w=.24){const g=new THREE.BufferGeometry();const verts=new Float32Array([0,0,0,-w*.55,.02,len*.42,0,.04,len,w*.55,.02,len*.42,0,0,0]);g.setAttribute('position',new THREE.BufferAttribute(verts,3));g.setIndex([0,1,2,0,2,3]);g.computeVertexNormals();return g}
export function createNaturalConifer({seed=1,scale=1}={}){
  const r=rng(seed),g=new THREE.Group(),dummy=new THREE.Object3D();
  g.name=`conifer_natural_v2_${seed}`;
  const h=(5.3+r()*.8)*scale;
  const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16*scale,.34*scale,h,10),bark);
  trunk.position.y=h*.5; trunk.castShadow=true; trunk.receiveShadow=true; g.add(trunk);
  const branchSpecs=[],frondSpecs=[[],[],[]];
  const levels=9;
  for(let lv=0;lv<levels;lv++){
    const y=.9+lv*(h*.073),norm=lv/(levels-1),rad=(1.65*(1-norm*.72)+.18)*scale,count=7+(lv%3);
    for(let i=0;i<count;i++){
      const a=i/count*Math.PI*2+(r()-.5)*.24,len=rad*(.72+r()*.34);
      branchSpecs.push({x:Math.cos(a)*len*.43,y,z:Math.sin(a)*len*.43,a,len});
      for(let sp=0;sp<3;sp++){
        const flen=(.62+r()*.25)*scale,fw=(.17+r()*.08)*scale,mi=(lv+sp+i)%3,d=len*(.38+sp*.22);
        frondSpecs[mi].push({x:Math.cos(a)*d,y:y+(sp-1)*.08*scale,z:Math.sin(a)*d,rx:-.18-r()*.14,ry:-a+Math.PI/2+(r()-.5)*.18,rz:(r()-.5)*.16,flen,fw});
      }
    }
  }
  const branchGeo=new THREE.CylinderGeometry(.025*scale,.06*scale,1,5),branches=new THREE.InstancedMesh(branchGeo,bark,branchSpecs.length);
  branchSpecs.forEach((v,i)=>{dummy.position.set(v.x,v.y,v.z);dummy.rotation.set(0,-v.a,Math.PI/2.05);dummy.scale.set(1,v.len,1);dummy.updateMatrix();branches.setMatrixAt(i,dummy.matrix)});
  branches.instanceMatrix.needsUpdate=true;branches.castShadow=true;branches.receiveShadow=true;g.add(branches);
  const frondBase=frondGeometry(1,1),frondMats=[darkNeedle,midNeedle,lightNeedle];
  frondSpecs.forEach((list,mi)=>{const mesh=new THREE.InstancedMesh(frondBase,frondMats[mi],list.length);list.forEach((v,i)=>{dummy.position.set(v.x,v.y,v.z);dummy.rotation.set(v.rx,v.ry,v.rz);dummy.scale.set(v.fw,1,v.flen);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh)});
  const topGeo=new THREE.ConeGeometry(1,1,7),tops=new THREE.InstancedMesh(topGeo,midNeedle,6);
  for(let i=0;i<6;i++){const rad=(.52-i*.055)*scale;dummy.position.set(0,(h-.95+i*.18),0);dummy.rotation.set(0,r()*Math.PI,0);dummy.scale.set(rad,.85*scale,rad);dummy.updateMatrix();tops.setMatrixAt(i,dummy.matrix)}tops.instanceMatrix.needsUpdate=true;tops.castShadow=true;tops.receiveShadow=true;g.add(tops);
  const needleGeo=new THREE.ConeGeometry(1,1,5),needles=new THREE.InstancedMesh(needleGeo,lightNeedle,9);
  for(let i=0;i<9;i++){dummy.position.set((r()-.5)*.75*scale,.16*scale,(r()-.5)*.75*scale);dummy.rotation.set(0,0,(r()-.5)*.8);dummy.scale.set(.06*scale,.35*scale,.06*scale);dummy.updateMatrix();needles.setMatrixAt(i,dummy.matrix)}needles.instanceMatrix.needsUpdate=true;needles.castShadow=true;needles.receiveShadow=true;g.add(needles);
  g.userData={assetId:'conifer_natural_v2',version:'2.1.0',seed,rendering:'instanced-v1'};
  return g;
}
export function createUnderstoryCluster({seed=1,scale=1,flowers=true}={}){
  const r=rng(seed),g=new THREE.Group(),dummy=new THREE.Object3D();
  const bladeGeo=new THREE.ConeGeometry(.035,.42,4),bladeMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1,side:THREE.DoubleSide});
  const blades=new THREE.InstancedMesh(bladeGeo,bladeMat,18),bladeColors=[new THREE.Color(0x5f8b3d),new THREE.Color(0x86a94b),new THREE.Color(0x497a38)];
  for(let i=0;i<18;i++){const h=(.22+r()*.42)*scale,w=(.025+r()*.035)*scale,a=r()*Math.PI*2,rr=r()*.72*scale;dummy.position.set(Math.cos(a)*rr,h*.48,Math.sin(a)*rr);dummy.rotation.set(0,r()*Math.PI*2,(r()-.5)*.45);dummy.scale.set(w/.035,h/.42,w/.035);dummy.updateMatrix();blades.setMatrixAt(i,dummy.matrix);blades.setColorAt(i,bladeColors[i%bladeColors.length])}
  blades.instanceMatrix.needsUpdate=true;if(blades.instanceColor)blades.instanceColor.needsUpdate=true;blades.receiveShadow=true;g.add(blades);
  const stemGeo=new THREE.CylinderGeometry(.012,.018,1,5),stems=new THREE.InstancedMesh(stemGeo,grass,7),flowerSpecs=[];
  for(let i=0;i<7;i++){const a=r()*Math.PI*2,rr=(.1+r()*.65)*scale,h=(.24+r()*.22)*scale,x=Math.cos(a)*rr,z=Math.sin(a)*rr;dummy.position.set(x,h*.5,z);dummy.rotation.set(0,r()*Math.PI*2,(r()-.5)*.15);dummy.scale.set(scale, h, scale);dummy.updateMatrix();stems.setMatrixAt(i,dummy.matrix);if(flowers&&i<4)flowerSpecs.push({x,y:h+.03*scale+r()*.04,z,c:i%2})}
  stems.instanceMatrix.needsUpdate=true;stems.receiveShadow=true;g.add(stems);
  if(flowerSpecs.length){const flowerGeo=new THREE.IcosahedronGeometry(.045*scale,0),flowerMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.8}),heads=new THREE.InstancedMesh(flowerGeo,flowerMat,flowerSpecs.length);const colors=[new THREE.Color(0xf6efd7),new THREE.Color(0xe7a3b0)];flowerSpecs.forEach((v,i)=>{dummy.position.set(v.x,v.y,v.z);dummy.rotation.set(0,r()*Math.PI*2,0);dummy.scale.setScalar(.85+r()*.35);dummy.updateMatrix();heads.setMatrixAt(i,dummy.matrix);heads.setColorAt(i,colors[v.c])});heads.instanceMatrix.needsUpdate=true;if(heads.instanceColor)heads.instanceColor.needsUpdate=true;g.add(heads)}
  g.userData={assetId:'understory_cluster_v2',version:'2.1.0',rendering:'instanced-v1'};return shadows(g)
}
export function createMeadowField({seed=1,width=12,depth=5,density=260,flowers=44}={}){const r=rng(seed),g=new THREE.Group(),dummy=new THREE.Object3D();const bladeGeo=new THREE.ConeGeometry(.032,.36,3),bladeMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:1});const blades=new THREE.InstancedMesh(bladeGeo,bladeMat,density);const greens=[new THREE.Color(0x436f32),new THREE.Color(0x5f8b3d),new THREE.Color(0x78a64a),new THREE.Color(0x94b55a)];for(let i=0;i<density;i++){const h=.55+r()*.85;dummy.position.set((r()-.5)*width,.12+r()*.03,(r()-.5)*depth);dummy.rotation.set((r()-.5)*.22,r()*Math.PI*2,(r()-.5)*.38);dummy.scale.set(.65+r()*.75,h,.65+r()*.55);dummy.updateMatrix();blades.setMatrixAt(i,dummy.matrix);blades.setColorAt(i,greens[(i+Math.floor(r()*greens.length))%greens.length])}blades.instanceMatrix.needsUpdate=true;if(blades.instanceColor)blades.instanceColor.needsUpdate=true;blades.castShadow=false;blades.receiveShadow=true;g.add(blades);const flowerGeo=new THREE.IcosahedronGeometry(.045,0),flowerMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.8}),heads=new THREE.InstancedMesh(flowerGeo,flowerMat,flowers);const colors=[new THREE.Color(0xf6efd7),new THREE.Color(0xe7a3b0),new THREE.Color(0xdac96b),new THREE.Color(0xb5c7ee)];for(let i=0;i<flowers;i++){dummy.position.set((r()-.5)*width,.25+r()*.18,(r()-.5)*depth);dummy.rotation.set(0,r()*Math.PI*2,0);const sc=.65+r()*.75;dummy.scale.setScalar(sc);dummy.updateMatrix();heads.setMatrixAt(i,dummy.matrix);heads.setColorAt(i,colors[i%colors.length])}heads.instanceMatrix.needsUpdate=true;if(heads.instanceColor)heads.instanceColor.needsUpdate=true;heads.castShadow=false;g.add(heads);g.userData={assetId:'meadow_field_v1',version:'1.0.0',instances:density+flowers};return g}
export function createLayeredBank({seed=1,width=13,depth=10,facing=1}={}){const r=rng(seed),g=new THREE.Group();g.name=`layered_bank_v2_${seed}`;const topGeo=new THREE.PlaneGeometry(width,depth,18,14),p=topGeo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin(x*.7+seed)*.11+Math.cos(y*.8)*.07+(r()-.5)*.09)}topGeo.computeVertexNormals();const topMat=new THREE.MeshStandardMaterial({color:0xffffff,map:makeGrassMap(seed,Math.max(2,width/4),Math.max(2,depth/4)),roughness:.99});const top=new THREE.Mesh(topGeo,topMat);top.rotation.x=-Math.PI/2;top.receiveShadow=true;g.add(top);const edgeZ=facing*(depth*.5-.3);const rockCount=Math.ceil(width/1.05);for(let i=0;i<rockCount;i++){const x=-width*.5+(i+.5)*width/rockCount+(r()-.5)*.32;const layers=2+(i%3===0?1:0);for(let layer=0;layer<layers;layer++){const rad=.55+r()*.42,geo=deform(new THREE.DodecahedronGeometry(rad,1),r,.3),m=new THREE.Mesh(geo,rockMats[(i+layer)%rockMats.length]);m.scale.set(.95+r()*.55,.65+r()*.55,.75+r()*.5);m.position.set(x+(r()-.5)*.25,-.48-layer*.63,edgeZ+(r()-.5)*.32);m.rotation.set(r()*.35,r()*Math.PI,r()*.2);g.add(m)}}const soilBand=new THREE.Mesh(new THREE.BoxGeometry(width*.97,.36,.68),soil);soilBand.position.set(0,-.25,edgeZ-facing*.16);g.add(soilBand);for(let i=0;i<Math.ceil(width/1.25);i++){const u=createUnderstoryCluster({seed:seed*17+i*13,scale:.48+r()*.42,flowers:i%3!==1});u.position.set(-width*.46+i*(width*.92/Math.max(1,Math.ceil(width/1.25)-1))+(r()-.5)*.35,.02,edgeZ-facing*(.38+r()*.55));g.add(u)}g.userData={assetId:'layered_bank_v2',version:'2.1.0'};return shadows(g)}
function foamStrip(width,depth,z,seed=1){const r=rng(seed),segments=54,verts=[],idx=[];for(let i=0;i<=segments;i++){const x=-width/2+width*i/segments;const wave=Math.sin(i*.72+seed)*.07+Math.sin(i*.21)*.05+(r()-.5)*.025;verts.push(x,.025,z+wave,x,.025,z+wave+(z>0?-.14:.14));if(i<segments){const a=i*2,b=a+1,c=a+2,d=a+3;idx.push(a,c,b,b,c,d)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return new THREE.Mesh(g,new THREE.MeshBasicMaterial({color:0xd7fbf5,transparent:true,opacity:.38,side:THREE.DoubleSide,depthWrite:false}))}
export function createRichWater({width=28,depth=6.2}={}){const g=new THREE.Group(),uniforms={uTime:{value:0},uDeep:{value:new THREE.Color(0x064e72)},uMid:{value:new THREE.Color(0x078eaa)},uLight:{value:new THREE.Color(0x8be9df)}};const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms,vertexShader:`varying vec2 vUv;varying float vWave;uniform float uTime;void main(){vUv=uv;vec3 p=position;float w=sin((p.x+uTime*.9)*1.7)*.055+cos((p.y-uTime*.55)*2.8)*.035+sin((p.x+p.y+uTime)*4.1)*.012;p.z+=w;vWave=w;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`varying vec2 vUv;varying float vWave;uniform vec3 uDeep;uniform vec3 uMid;uniform vec3 uLight;uniform float uTime;void main(){float bands=.5+.5*sin(vUv.x*58.+vUv.y*37.+uTime*3.1);float spark=smoothstep(.82,.98,sin(vUv.x*117.+uTime*5.)*sin(vUv.y*91.-uTime*3.));float shore=1.-smoothstep(0.,.14,min(vUv.y,1.-vUv.y));vec3 c=mix(uDeep,uMid,.28+vUv.y*.2+bands*.08);c=mix(c,uLight,spark*.45+shore*.2+abs(vWave)*1.8);gl_FragColor=vec4(c,.9);}`});const water=new THREE.Mesh(new THREE.PlaneGeometry(width,depth,64,24),mat);water.rotation.x=-Math.PI/2;g.add(water);g.add(foamStrip(width,depth,depth*.49,17),foamStrip(width,depth,-depth*.49,23));for(let i=0;i<5;i++){const rr=rng(i+90),geo=deform(new THREE.DodecahedronGeometry(.32+rr()*.4,1),rr,.25),rock=new THREE.Mesh(geo,rockMats[i%4]);rock.position.set(-width*.36+i*(width*.72/4)+(rr()-.5)*1.2,.05,(rr()-.5)*depth*.5);rock.scale.y=.7;g.add(rock)}g.userData={assetId:'water_rich_v2',version:'2.1.0',update:t=>uniforms.uTime.value=t};return g}
export function naturalAssetMetadata(){return{tree:'conifer_natural_v2@2.1.0',bank:'layered_bank_v2@2.1.0',water:'water_rich_v2@2.1.0',understory:'understory_cluster_v2@2.1.0',meadow:'meadow_field_v1@1.0.0'}}