(() => {
'use strict';

/* Collision-safe add-on: functional street bakery and field-only healing food. */
const BREAD_PRICE=6,BREAD_HEAL=12;
s.bread=Number.isFinite(Number(s.bread))?Math.max(0,Math.floor(Number(s.bread))):0;s.bakeryOpen=false;
const style=document.createElement('style');style.textContent=`
.lqBakeryOverlay{position:absolute;inset:0;z-index:54;display:flex;align-items:flex-end;justify-content:center;padding:12px;background:#02070aa8;backdrop-filter:blur(2px)}.lqBakeryPanel{width:min(360px,94%);padding:12px;border-radius:15px;background:linear-gradient(180deg,#3a281b,#1b1612);border:2px solid #c89958;box-shadow:0 15px 34px #000c,inset 0 0 25px #dcaa5a12}.lqBakeryTitle{display:flex;justify-content:space-between;align-items:end;color:#ffe1a0;font-family:Georgia,serif;font-size:18px;font-weight:900}.lqBakeryTitle small{font-family:inherit;color:#b89d76;font-size:8px;letter-spacing:.12em}.lqBakeryGood{margin:10px 0;padding:9px;border-radius:9px;background:#211a14;border:1px solid #ffffff12}.lqBakeryGood b{color:#f3d6a0;font-size:12px}.lqBakeryGood span{float:right;color:#e0b95f;font-weight:900}.lqBakeryGood p{margin:4px 0 0;color:#a99680;font-size:8px;line-height:1.45}.lqBakeryBtns{display:grid;grid-template-columns:1fr 1fr;gap:7px}.lqBakeryBtns button{min-height:46px;border-radius:9px;border:1px solid #ffffff18;background:#604527;color:#f1d6a0;font-weight:900}.lqBakeryBtns button:disabled{opacity:.35}.lqBakeryBtns .close{background:#293440;color:#c4d0d7}.lqBreadChip{border-color:#b8894d55!important;background:#30251a!important}.lqBreadUse{min-height:34px;border-radius:7px;border:1px solid #c99a5a44;background:#4b3723;color:#efd5a1;font-size:8px;font-weight:900}
`;document.head.appendChild(style);
function bakerAhead(){if(s.screen!=='world'||s.map!=='town')return false;const p=front();return currentNpcs().some(n=>n.x===p.x&&n.y===p.y&&n.name==='パン屋のトーマ');}
window.lqCloseBakery=function(){s.bakeryOpen=false;render();};
window.lqBuyBread=function(){if(!s.bakeryOpen||s.gold<BREAD_PRICE)return;s.gold-=BREAD_PRICE;s.bread++;save();window.LQ_sfx?.('menu');render();};
window.lqUseBread=function(){if(s.screen!=='world'||s.bread<=0||s.hp>=s.mh)return;s.bread--;const before=s.hp;s.hp=Math.min(s.mh,s.hp+BREAD_HEAL);save();s.pauseOpen=false;s.dialog={name:'ルーク',text:`焼きパンを食べた。HPが ${s.hp-before} 回復した。\nルーク「薬草より、こっちを戦闘中に食べたいです。」`};window.LQ_sfx?.('heal');render();};
function addBakery(){if(!s.bakeryOpen||s.screen!=='world')return;const shell=app.querySelector('.gameShell');if(!shell||shell.querySelector('.lqBakeryOverlay'))return;shell.insertAdjacentHTML('beforeend',`<div class=lqBakeryOverlay><div class=lqBakeryPanel><div class=lqBakeryTitle>トーマの焼きパン <small>STREET BAKERY</small></div><div class=lqBakeryGood><b>焼きパン</b><span>${BREAD_PRICE}G</span><p>香ばしい朝焼きパン。フィールドでHPを${BREAD_HEAL}回復。戦闘中は食べられない。<br>所持 ${s.bread}個 / GOLD ${s.gold}G</p></div><div class=lqBakeryBtns><button ${s.gold<BREAD_PRICE?'disabled':''} onclick=lqBuyBread()>1個買う</button><button class=close onclick=lqCloseBakery()>閉じる</button></div></div></div>`);}
function addBreadMenu(){if(!s.pauseOpen||s.bread<=0)return;const row=app.querySelector('.lqInventoryRow');if(!row||row.querySelector('.lqBreadChip'))return;const chip=document.createElement('div');chip.className='lqItemChip lqBreadChip';chip.innerHTML=`焼きパン <strong>×${s.bread}</strong>${s.hp<s.mh?'<br><button class=lqBreadUse onclick=lqUseBread()>食べる</button>':''}`;row.appendChild(chip);}
const actionBakeryBase=action;action=function(){if(s.bakeryOpen)return lqCloseBakery();if(!s.dialog&&bakerAhead()){stopMoving();s.bakeryOpen=true;return render();}return actionBakeryBase();};
const moveBakeryBase=move;move=function(d){if(s.bakeryOpen){stopMoving();return}return moveBakeryBase(d);};
const worldBakeryBase=world;world=function(){worldBakeryBase();addBakery();addBreadMenu();};const renderBakeryBase=render;render=function(){const r=renderBakeryBase();addBakery();addBreadMenu();return r;};window.LQ_BAKERY_STATUS={vendor:'パン屋のトーマ',breadPrice:BREAD_PRICE,fieldHeal:BREAD_HEAL,battleUsable:false};save();addBakery();addBreadMenu();
})();
